<?php

namespace App\Controller;

class LogoutController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Auth->deny(['index']);
    }

    /**
     * @return \Cake\Http\Response|null
     */
    public function index()
    {
        $this->Flash->success('Logoutしました');
        return $this->redirect($this->Auth->logout());
    }


}
